- id: go-fmt-import
  name: 'go import/fmt'
  entry: run-go-fmt-import.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'goimport,gofmt', requires golang"

- id: go-vet
  name: 'go vet'
  entry: run-go-vet.sh
  files: '\.go$'
  language: 'script'
  description: "Run 'go vet', requires golang"

- id: go-lint
  name: 'golint'
  entry: run-go-lint.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'go lint', requires golang"

- id: go-unit-tests
  name: 'go unit test'
  entry: run-go-unit-tests.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'go test', requires golang"

- id: gofumpt
  name: 'gofumpt'
  entry: run-go-fumpt.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'gofumpt', requires github.com/mvdan/gofumpt"

- id: go-err-check
  name: 'go errcheck'
  entry: run-go-err-check.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'errcheck', requires github.com/kisielk/errcheck"

- id: go-static-check
  name: 'go staticcheck'
  entry: run-go-static-check.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'staticcheck', install https://staticcheck.io.docs/"

- id: golangci-lint
  name: 'go golangci-lint'
  entry: run-golangci-lint.sh
  files: '\.go$'
  language: 'script'
  description: "Runs 'golangci-lint', install https://github.com/golangci/golangci-lint"

- id: commitmsg-check
  name: 'commitmsg-check'
  entry: run-commitmsg-check.sh
  language: 'script'
  description: "Validate recently git commit message against commit format provided by git karma http://karma-runner.github.io/6.3/dev/git-commit-msg.html"
